language: go

go:
  - 1.12.x

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

before_script:
  - golangci-lint run
  - go vet ./...

script:
  - go test -v ./...
